services:
  - type: web
    name: allinol-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        fromService:
          name: allinol-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
          append: /api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /tasks
        destination: /index.html
      - type: rewrite
        source: /tasks/*
        destination: /index.html
      - type: rewrite
        source: /ai-chat
        destination: /index.html
      - type: rewrite
        source: /ai-workflow
        destination: /index.html
      - type: rewrite
        source: /admin/*
        destination: /index.html 