services:
  - type: web
    name: allinol-api
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-specdec
      - key: GROQ_RATE_LIMIT
        value: 60
    healthCheckPath: /health

  - type: web
    name: allinol-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: allinol-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
          append: /api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 